"""
Country-Species Mapping for IUCN Red List
Curated list of representative endangered species by country
"""

# ========================================
# 국가별 대표 멸종위기종 학명 리스트
# ========================================
# 카테고리: 동물, 식물, 곤충, 해양생물
# 각 국가당 카테고리별 5-10개 종의 학명을 정의
# ========================================

COUNTRY_SPECIES_MAP = {
    "KR": {
        "동물": [
            "Grus japonensis",
            "Naemorhedus caudatus",
            "Ursus thibetanus",
            "Lutra lutra",
            "Moschus moschiferus",
            "Mustela lutreola",
            "Falco peregrinus",
            "Haliaeetus pelagicus",
            "Ciconia boyciana",
        ],
        "식물": [
            "Magnolia sieboldii",
            "Pinus koraiensis",
            "Taxus cuspidata",
            "Rhododendron aureum",
            "Abies koreana",
        ],
        "곤충": [
            "Teinopalpus imperialis",
            "Lucanus maculifemoratus",
            "Callipogon relictus",
            "Rosalia batesi",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },
    
    "US": {
        "동물": [
            "Haliaeetus leucocephalus",
            "Ursus arctos horribilis",
            "Lynx canadensis",
            "Puma concolor",
            "Canis lupus",
            "Mustela nigripes",
            "Grus americana",
            "Gymnogyps californianus",
            "Alligator mississippiensis",
        ],
        "식물": [
            "Sequoia sempervirens",
            "Pinus ponderosa",
            "Quercus alba",
            "Acer saccharum",
            "Betula papyrifera",
        ],
        "곤충": [
            "Dynastes tityus",
            "Lucanus elaphus",
            "Nicrophorus americanus",
            "Danaus plexippus",
        ],
        "해양생물": [
            "Caretta caretta",
            "Chelonia mydas",
            "Balaenoptera musculus",
            "Carcharodon carcharias",
            "Megaptera novaeangliae",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Dugong dugon",
        ],
    },
    
    "JP": {
        "동물": [
            "Grus japonensis",
            "Ursus thibetanus",
            "Lutra lutra",
            "Prionailurus bengalensis",
            "Nipponia nippon",
            "Haliaeetus pelagicus",
            "Falco peregrinus",
            "Cervus nippon",
            "Macaca fuscata",
        ],
        "식물": [
            "Magnolia sieboldii",
            "Pinus koraiensis",
            "Taxus cuspidata",
            "Rhododendron aureum",
            "Abies koreana",
        ],
        "곤충": [
            "Teinopalpus imperialis",
            "Lucanus maculifemoratus",
            "Callipogon relictus",
            "Rosalia batesi",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
            "Trichechus manatus",
        ],
    },
    
    "CN": {
        "동물": [
            "Ailuropoda melanoleuca",
            "Panthera tigris amoyensis",
            "Panthera uncia",
            "Rhinopithecus roxellana",
            "Ursus thibetanus",
            "Moschus moschiferus",
            "Grus japonensis",
            "Nipponia nippon",
            "Crocodylus siamensis",
        ],
        "식물": [
            "Magnolia sieboldii",
            "Pinus koraiensis",
            "Taxus cuspidata",
            "Rhododendron aureum",
            "Abies koreana",
        ],
        "곤충": [
            "Teinopalpus imperialis",
            "Lucanus maculifemoratus",
            "Callipogon relictus",
            "Rosalia batesi",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
            "Lipotes vexillifer",
        ],
    },
    
    "RU": {
        "동물": [
            "Panthera tigris altaica",
            "Ursus maritimus",
            "Panthera uncia",
            "Grus leucogeranus",
            "Haliaeetus pelagicus",
            "Ursus arctos",
            "Mustela lutreola",
            "Balaena mysticetus",
            "Moschus moschiferus",
            "Saiga tatarica",
        ],
        "식물": [
            "Magnolia sieboldii",
            "Pinus koraiensis",
            "Taxus cuspidata",
            "Rhododendron aureum",
            "Abies koreana",
        ],
        "곤충": [
            "Teinopalpus imperialis",
            "Lucanus maculifemoratus",
            "Callipogon relictus",
            "Rosalia batesi",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },
    
    "AU": {
        "동물": [
            "Phascolarctos cinereus",
            "Macropus rufus",
            "Vombatus ursinus",
            "Ornithorhynchus anatinus",
            "Tachyglossus aculeatus",
            "Crocodylus porosus",
            "Chelonia mydas",
            "Carcharodon carcharias",
            "Dugong dugon",
            "Dasyurus viverrinus",
        ],
        "식물": [
            "Eucalyptus regnans",
            "Acacia pycnantha",
            "Araucaria cunninghamii",
            "Ficus macrophylla",
            "Banksia serrata",
        ],
        "곤충": [
            "Ornithoptera alexandrae",
            "Papilio ulysses",
            "Phalacrognathus muelleri",
            "Lamprima aurata",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },
    
    "BR": {
        "동물": [
            "Panthera onca",
            "Tapirus terrestris",
            "Ara ararauna",
            "Pteronura brasiliensis",
            "Myrmecophaga tridactyla",
            "Priodontes maximus",
            "Bradypus variegatus",
            "Leontopithecus rosalia",
            "Trichechus manatus",
            "Chelonia mydas",
        ],
        "식물": [
            "Bertholletia excelsa",
            "Hevea brasiliensis",
            "Theobroma cacao",
            "Cinchona pubescens",
            "Victoria amazonica",
        ],
        "곤충": [
            "Dynastes hercules",
            "Megasoma elephas",
            "Morpho menelaus",
            "Titanus giganteus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },
    
    "IN": {
        "동물": [
            "Panthera tigris",
            "Panthera leo persica",
            "Elephas maximus",
            "Rhinoceros unicornis",
            "Panthera pardus",
            "Ursus thibetanus",
            "Bos gaurus",
            "Cuon alpinus",
            "Gavialis gangeticus",
            "Grus antigone",
        ],
        "식물": [
            "Magnolia sieboldii",
            "Pinus koraiensis",
            "Taxus cuspidata",
            "Rhododendron aureum",
            "Abies koreana",
        ],
        "곤충": [
            "Teinopalpus imperialis",
            "Lucanus maculifemoratus",
            "Callipogon relictus",
            "Rosalia batesi",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },
    
    "ZA": {
        "동물": [
            "Panthera leo",
            "Loxodonta africana",
            "Diceros bicornis",
            "Ceratotherium simum",
            "Panthera pardus",
            "Acinonyx jubatus",
            "Lycaon pictus",
            "Hippopotamus amphibius",
            "Giraffa camelopardalis",
            "Carcharodon carcharias",
        ],
        "식물": [
            "Acacia tortilis",
            "Adansonia digitata",
            "Aloe vera",
            "Euphorbia tirucalli",
            "Commiphora myrrha",
        ],
        "곤충": [
            "Goliathus goliatus",
            "Mecynorrhina torquata",
            "Charaxes jasius",
            "Mylabris oculata",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "CA": {
        "동물": [
            "Ursus maritimus",
            "Rangifer tarandus",
            "Canis lupus",
            "Ursus arctos",
            "Lynx canadensis",
            "Gulo gulo",
            "Puma concolor",
            "Alces alces",
            "Balaena mysticetus",
            "Haliaeetus leucocephalus",
        ],
        "식물": [
            "Sequoia sempervirens",
            "Pinus ponderosa",
            "Quercus alba",
            "Acer saccharum",
            "Betula papyrifera",
        ],
        "곤충": [
            "Dynastes tityus",
            "Lucanus elaphus",
            "Nicrophorus americanus",
            "Danaus plexippus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "MX": {
        "동물": [
            "Panthera onca",
            "Tapirus bairdii",
            "Trichechus manatus",
            "Alouatta palliata",
            "Ara militaris",
            "Chelonia mydas",
            "Crocodylus acutus",
            "Gopherus flavomarginatus",
            "Ambystoma mexicanum",
            "Antilocapra americana",
        ],
        "식물": [
            "Sequoia sempervirens",
            "Pinus ponderosa",
            "Quercus alba",
            "Acer saccharum",
            "Betula papyrifera",
        ],
        "곤충": [
            "Dynastes tityus",
            "Lucanus elaphus",
            "Nicrophorus americanus",
            "Danaus plexippus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "AR": {
        "동물": [
            "Panthera onca",
            "Puma concolor",
            "Chrysocyon brachyurus",
            "Myrmecophaga tridactyla",
            "Pteronura brasiliensis",
            "Ara glaucogularis",
            "Hippocamelus bisulcus",
            "Chinchilla chinchilla",
            "Eubalaena australis",
            "Ctenomys sociabilis",
        ],
        "식물": [
            "Bertholletia excelsa",
            "Hevea brasiliensis",
            "Theobroma cacao",
            "Cinchona pubescens",
            "Victoria amazonica",
        ],
        "곤충": [
            "Dynastes hercules",
            "Megasoma elephas",
            "Morpho menelaus",
            "Titanus giganteus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "GB": {
        "동물": [
            "Lutra lutra",
            "Mustela putorius",
            "Sciurus vulgaris",
            "Halichoerus grypus",
            "Erinaceus europaeus",
            "Falco peregrinus",
            "Bubo bubo",
            "Salmo salar",
            "Phocoena phocoena",
            "Bufo bufo",
        ],
        "식물": [
            "Taxus baccata",
            "Pinus sylvestris",
            "Betula pendula",
            "Quercus robur",
            "Fagus sylvatica",
        ],
        "곤충": [
            "Lucanus cervus",
            "Cerambyx cerdo",
            "Rosalia alpina",
            "Carabus auratus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "FR": {
        "동물": [
            "Ursus arctos",
            "Lynx lynx",
            "Canis lupus",
            "Lutra lutra",
            "Vulpes vulpes",
            "Gypaetus barbatus",
            "Aquila chrysaetos",
            "Testudo hermanni",
            "Monachus monachus",
            "Phoca vitulina",
        ],
        "식물": [
            "Taxus baccata",
            "Pinus sylvestris",
            "Betula pendula",
            "Quercus robur",
            "Fagus sylvatica",
        ],
        "곤충": [
            "Lucanus cervus",
            "Cerambyx cerdo",
            "Rosalia alpina",
            "Carabus auratus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "DE": {
        "동물": [
            "Lynx lynx",
            "Canis lupus",
            "Lutra lutra",
            "Castor fiber",
            "Ursus arctos",
            "Mustela lutreola",
            "Aquila chrysaetos",
            "Haliaeetus albicilla",
            "Grus grus",
            "Bombina bombina",
        ],
        "식물": [
            "Taxus baccata",
            "Pinus sylvestris",
            "Betula pendula",
            "Quercus robur",
            "Fagus sylvatica",
        ],
        "곤충": [
            "Lucanus cervus",
            "Cerambyx cerdo",
            "Rosalia alpina",
            "Carabus auratus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "IT": {
        "동물": [
            "Ursus arctos marsicanus",
            "Canis lupus",
            "Lynx lynx",
            "Rupicapra pyrenaica ornata",
            "Caretta caretta",
            "Monachus monachus",
            "Testudo hermanni",
            "Aquila chrysaetos",
            "Gypaetus barbatus",
            "Salamandrina perspicillata",
        ],
        "식물": [
            "Taxus baccata",
            "Pinus sylvestris",
            "Betula pendula",
            "Quercus robur",
            "Fagus sylvatica",
        ],
        "곤충": [
            "Lucanus cervus",
            "Cerambyx cerdo",
            "Rosalia alpina",
            "Carabus auratus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "ID": {
        "동물": [
            "Pongo abelii",
            "Pongo pygmaeus",
            "Panthera tigris sumatrae",
            "Rhinoceros sondaicus",
            "Dicerorhinus sumatrensis",
            "Elephas maximus sumatranus",
            "Varanus komodoensis",
            "Manis javanica",
            "Crocodylus porosus",
            "Chelonia mydas",
        ],
        "식물": [
            "Magnolia sieboldii",
            "Pinus koraiensis",
            "Taxus cuspidata",
            "Rhododendron aureum",
            "Abies koreana",
        ],
        "곤충": [
            "Teinopalpus imperialis",
            "Lucanus maculifemoratus",
            "Callipogon relictus",
            "Rosalia batesi",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "KE": {
        "동물": [
            "Loxodonta africana",
            "Panthera leo",
            "Panthera pardus",
            "Diceros bicornis",
            "Acinonyx jubatus",
            "Giraffa camelopardalis",
            "Hippopotamus amphibius",
            "Equus grevyi",
            "Lycaon pictus",
            "Struthio camelus",
        ],
        "식물": [
            "Acacia tortilis",
            "Adansonia digitata",
            "Aloe vera",
            "Euphorbia tirucalli",
            "Commiphora myrrha",
        ],
        "곤충": [
            "Goliathus goliatus",
            "Mecynorrhina torquata",
            "Charaxes jasius",
            "Mylabris oculata",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "EG": {
        "동물": [
            "Panthera pardus",
            "Acinonyx jubatus",
            "Gazella dorcas",
            "Oryx dammah",
            "Addax nasomaculatus",
            "Crocodylus niloticus",
            "Caretta caretta",
            "Chelonia mydas",
            "Dugong dugon",
            "Tursiops truncatus",
        ],
        "식물": [
            "Acacia tortilis",
            "Adansonia digitata",
            "Aloe vera",
            "Euphorbia tirucalli",
            "Commiphora myrrha",
        ],
        "곤충": [
            "Goliathus goliatus",
            "Mecynorrhina torquata",
            "Charaxes jasius",
            "Mylabris oculata",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "TH": {
        "동물": [
            "Panthera tigris corbetti",
            "Elephas maximus",
            "Panthera pardus",
            "Bos gaurus",
            "Cuon alpinus",
            "Prionailurus bengalensis",
            "Crocodylus siamensis",
            "Chelonia mydas",
            "Dermochelys coriacea",
            "Gavialis gangeticus",
        ],
        "식물": [
            "Magnolia sieboldii",
            "Pinus koraiensis",
            "Taxus cuspidata",
            "Rhododendron aureum",
            "Abies koreana",
        ],
        "곤충": [
            "Teinopalpus imperialis",
            "Lucanus maculifemoratus",
            "Callipogon relictus",
            "Rosalia batesi",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "MY": {
        "동물": [
            "Panthera tigris jacksoni",
            "Elephas maximus",
            "Rhinoceros sondaicus",
            "Dicerorhinus sumatrensis",
            "Panthera pardus",
            "Helarctos malayanus",
            "Manis javanica",
            "Pongo pygmaeus",
            "Nasalis larvatus",
            "Crocodylus porosus",
        ],
        "식물": [
            "Magnolia sieboldii",
            "Pinus koraiensis",
            "Taxus cuspidata",
            "Rhododendron aureum",
            "Abies koreana",
        ],
        "곤충": [
            "Teinopalpus imperialis",
            "Lucanus maculifemoratus",
            "Callipogon relictus",
            "Rosalia batesi",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "NZ": {
        "동물": [
            "Apteryx haastii",
            "Strigops habroptilus",
            "Nestor meridionalis",
            "Megadyptes antipodes",
            "Carcharodon carcharias",
            "Arctocephalus forsteri",
            "Sphenodon punctatus",
            "Leiopelma hochstetteri",
            "Delphinapterus leucas",
            "Callorhinus ursinus",
        ],
        "식물": [
            "Eucalyptus regnans",
            "Acacia pycnantha",
            "Araucaria cunninghamii",
            "Ficus macrophylla",
            "Banksia serrata",
        ],
        "곤충": [
            "Ornithoptera alexandrae",
            "Papilio ulysses",
            "Phalacrognathus muelleri",
            "Lamprima aurata",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "SE": {
        "동물": [
            "Ursus arctos",
            "Canis lupus",
            "Lynx lynx",
            "Gulo gulo",
            "Rangifer tarandus",
            "Alces alces",
            "Halichoerus grypus",
            "Phoca vitulina",
            "Haliaeetus albicilla",
            "Aquila chrysaetos",
        ],
        "식물": [
            "Taxus baccata",
            "Pinus sylvestris",
            "Betula pendula",
            "Quercus robur",
            "Fagus sylvatica",
        ],
        "곤충": [
            "Lucanus cervus",
            "Cerambyx cerdo",
            "Rosalia alpina",
            "Carabus auratus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "NO": {
        "동물": [
            "Ursus maritimus",
            "Ursus arctos",
            "Canis lupus",
            "Lynx lynx",
            "Gulo gulo",
            "Rangifer tarandus",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Orcinus orca",
            "Halichoerus grypus",
        ],
        "식물": [
            "Taxus baccata",
            "Pinus sylvestris",
            "Betula pendula",
            "Quercus robur",
            "Fagus sylvatica",
        ],
        "곤충": [
            "Lucanus cervus",
            "Cerambyx cerdo",
            "Rosalia alpina",
            "Carabus auratus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "PL": {
        "동물": [
            "Bison bonasus",
            "Canis lupus",
            "Lynx lynx",
            "Ursus arctos",
            "Castor fiber",
            "Lutra lutra",
            "Aquila chrysaetos",
            "Haliaeetus albicilla",
            "Grus grus",
            "Ciconia nigra",
        ],
        "식물": [
            "Taxus baccata",
            "Pinus sylvestris",
            "Betula pendula",
            "Quercus robur",
            "Fagus sylvatica",
        ],
        "곤충": [
            "Lucanus cervus",
            "Cerambyx cerdo",
            "Rosalia alpina",
            "Carabus auratus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "ES": {
        "동물": [
            "Lynx pardinus",
            "Ursus arctos",
            "Canis lupus",
            "Aquila adalberti",
            "Gypaetus barbatus",
            "Monachus monachus",
            "Caretta caretta",
            "Testudo graeca",
            "Capra pyrenaica",
            "Rupicapra pyrenaica",
        ],
        "식물": [
            "Taxus baccata",
            "Pinus sylvestris",
            "Betula pendula",
            "Quercus robur",
            "Fagus sylvatica",
        ],
        "곤충": [
            "Lucanus cervus",
            "Cerambyx cerdo",
            "Rosalia alpina",
            "Carabus auratus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "TR": {
        "동물": [
            "Panthera pardus tulliana",
            "Ursus arctos",
            "Canis lupus",
            "Lynx lynx",
            "Capra aegagrus",
            "Gazella subgutturosa",
            "Monachus monachus",
            "Caretta caretta",
            "Testudo graeca",
            "Aquila chrysaetos",
        ],
        "식물": [
            "Taxus baccata",
            "Pinus sylvestris",
            "Betula pendula",
            "Quercus robur",
            "Fagus sylvatica",
        ],
        "곤충": [
            "Lucanus cervus",
            "Cerambyx cerdo",
            "Rosalia alpina",
            "Carabus auratus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "VN": {
        "동물": [
            "Panthera tigris",
            "Elephas maximus",
            "Rhinoceros sondaicus",
            "Bos sauveli",
            "Pseudoryx nghetinhensis",
            "Crocodylus siamensis",
            "Chelonia mydas",
            "Dermochelys coriacea",
            "Manis javanica",
            "Nomascus gabriellae",
        ],
        "식물": [
            "Magnolia sieboldii",
            "Pinus koraiensis",
            "Taxus cuspidata",
            "Rhododendron aureum",
            "Abies koreana",
        ],
        "곤충": [
            "Teinopalpus imperialis",
            "Lucanus maculifemoratus",
            "Callipogon relictus",
            "Rosalia batesi",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "PE": {
        "동물": [
            "Panthera onca",
            "Tremarctos ornatus",
            "Tapirus terrestris",
            "Pteronura brasiliensis",
            "Ara militaris",
            "Trichechus manatus",
            "Inia geoffrensis",
            "Crocodylus acutus",
            "Chelonia mydas",
            "Hippocamelus antisensis",
        ],
        "식물": [
            "Bertholletia excelsa",
            "Hevea brasiliensis",
            "Theobroma cacao",
            "Cinchona pubescens",
            "Victoria amazonica",
        ],
        "곤충": [
            "Dynastes hercules",
            "Megasoma elephas",
            "Morpho menelaus",
            "Titanus giganteus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "CL": {
        "동물": [
            "Puma concolor",
            "Hippocamelus bisulcus",
            "Lama guanicoe",
            "Vicugna vicugna",
            "Chinchilla chinchilla",
            "Lontra felina",
            "Arctocephalus philippii",
            "Balaenoptera musculus",
            "Eubalaena australis",
            "Spheniscus humboldti",
        ],
        "식물": [
            "Bertholletia excelsa",
            "Hevea brasiliensis",
            "Theobroma cacao",
            "Cinchona pubescens",
            "Victoria amazonica",
        ],
        "곤충": [
            "Dynastes hercules",
            "Megasoma elephas",
            "Morpho menelaus",
            "Titanus giganteus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "CO": {
        "동물": [
            "Panthera onca",
            "Tremarctos ornatus",
            "Tapirus terrestris",
            "Ateles fusciceps",
            "Saguinus oedipus",
            "Ara militaris",
            "Crocodylus acutus",
            "Chelonia mydas",
            "Trichechus manatus",
            "Inia geoffrensis",
        ],
        "식물": [
            "Bertholletia excelsa",
            "Hevea brasiliensis",
            "Theobroma cacao",
            "Cinchona pubescens",
            "Victoria amazonica",
        ],
        "곤충": [
            "Dynastes hercules",
            "Megasoma elephas",
            "Morpho menelaus",
            "Titanus giganteus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "NG": {
        "동물": [
            "Gorilla gorilla",
            "Pan troglodytes",
            "Loxodonta africana",
            "Panthera leo",
            "Panthera pardus",
            "Hippopotamus amphibius",
            "Trichechus senegalensis",
            "Crocodylus niloticus",
            "Chelonia mydas",
            "Manis tricuspis",
        ],
        "식물": [
            "Acacia tortilis",
            "Adansonia digitata",
            "Aloe vera",
            "Euphorbia tirucalli",
            "Commiphora myrrha",
        ],
        "곤충": [
            "Goliathus goliatus",
            "Mecynorrhina torquata",
            "Charaxes jasius",
            "Mylabris oculata",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },
}

# 국가 코드와 이름 매핑 (참고용)
COUNTRY_NAMES = {
    "KR": "South Korea",
    "US": "United States",
    "JP": "Japan",
    "CN": "China",
    "RU": "Russia",
    "AU": "Australia",
    "BR": "Brazil",
    "IN": "India",
    "ZA": "South Africa",
    "CA": "Canada",
    "MX": "Mexico",
    "AR": "Argentina",
    "GB": "United Kingdom",
    "FR": "France",
    "DE": "Germany",
    "IT": "Italy",
    "ID": "Indonesia",
    "KE": "Kenya",
    "EG": "Egypt",
    "TH": "Thailand",
    "MY": "Malaysia",
    "NZ": "New Zealand",
    "SE": "Sweden",
    "NO": "Norway",
    "PL": "Poland",
    "ES": "Spain",
    "TR": "Turkey",
    "VN": "Vietnam",
    "PE": "Peru",
    "CL": "Chile",
    "CO": "Colombia",
    "NG": "Nigeria",
}

# ========================================
# CONTINENT_SPECIES_MAP
# ========================================
# 대륙별 대표 멸종위기종 (Regional Fallback Pattern)
# 특정 국가 데이터가 없을 때 대륙 단위로 fallback
# ========================================

CONTINENT_SPECIES_MAP = {
    "AS": {
        "동물": [
            "Panthera tigris",
            "Ailuropoda melanoleuca",
            "Panthera uncia",
            "Elephas maximus",
            "Pongo abelii",
            "Rhinoceros sondaicus",
            "Grus japonensis",
            "Ursus thibetanus",
            "Naemorhedus caudatus",
            "Crocodylus siamensis",
        ],
        "식물": [
            "Magnolia sieboldii",
            "Pinus koraiensis",
            "Taxus cuspidata",
            "Rhododendron aureum",
            "Abies koreana",
        ],
        "곤충": [
            "Teinopalpus imperialis",
            "Lucanus maculifemoratus",
            "Callipogon relictus",
            "Rosalia batesi",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "EU": {
        "동물": [
            "Ursus arctos",
            "Lynx lynx",
            "Canis lupus",
            "Lynx pardinus",
            "Bison bonasus",
            "Lutra lutra",
            "Aquila chrysaetos",
            "Gypaetus barbatus",
            "Monachus monachus",
            "Castor fiber",
        ],
        "식물": [
            "Taxus baccata",
            "Pinus sylvestris",
            "Betula pendula",
            "Quercus robur",
            "Fagus sylvatica",
        ],
        "곤충": [
            "Lucanus cervus",
            "Cerambyx cerdo",
            "Rosalia alpina",
            "Carabus auratus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "AF": {
        "동물": [
            "Loxodonta africana",
            "Panthera leo",
            "Diceros bicornis",
            "Panthera pardus",
            "Acinonyx jubatus",
            "Giraffa camelopardalis",
            "Gorilla gorilla",
            "Hippopotamus amphibius",
            "Lycaon pictus",
            "Crocodylus niloticus",
        ],
        "식물": [
            "Acacia tortilis",
            "Adansonia digitata",
            "Aloe vera",
            "Euphorbia tirucalli",
            "Commiphora myrrha",
        ],
        "곤충": [
            "Goliathus goliatus",
            "Mecynorrhina torquata",
            "Charaxes jasius",
            "Mylabris oculata",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "NA": {
        "동물": [
            "Haliaeetus leucocephalus",
            "Ursus arctos horribilis",
            "Ursus maritimus",
            "Canis lupus",
            "Puma concolor",
            "Lynx canadensis",
            "Grus americana",
            "Mustela nigripes",
            "Alligator mississippiensis",
            "Gymnogyps californianus",
        ],
        "식물": [
            "Sequoia sempervirens",
            "Pinus ponderosa",
            "Quercus alba",
            "Acer saccharum",
            "Betula papyrifera",
        ],
        "곤충": [
            "Dynastes tityus",
            "Lucanus elaphus",
            "Nicrophorus americanus",
            "Danaus plexippus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "SA": {
        "동물": [
            "Panthera onca",
            "Tapirus terrestris",
            "Pteronura brasiliensis",
            "Myrmecophaga tridactyla",
            "Tremarctos ornatus",
            "Ara ararauna",
            "Leontopithecus rosalia",
            "Bradypus variegatus",
            "Inia geoffrensis",
            "Trichechus manatus",
        ],
        "식물": [
            "Bertholletia excelsa",
            "Hevea brasiliensis",
            "Theobroma cacao",
            "Cinchona pubescens",
            "Victoria amazonica",
        ],
        "곤충": [
            "Dynastes hercules",
            "Megasoma elephas",
            "Morpho menelaus",
            "Titanus giganteus",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "OC": {
        "동물": [
            "Phascolarctos cinereus",
            "Macropus rufus",
            "Ornithorhynchus anatinus",
            "Apteryx haastii",
            "Strigops habroptilus",
            "Crocodylus porosus",
            "Dugong dugon",
            "Carcharodon carcharias",
            "Megadyptes antipodes",
            "Chelonia mydas",
        ],
        "식물": [
            "Eucalyptus regnans",
            "Acacia pycnantha",
            "Araucaria cunninghamii",
            "Ficus macrophylla",
            "Banksia serrata",
        ],
        "곤충": [
            "Ornithoptera alexandrae",
            "Papilio ulysses",
            "Phalacrognathus muelleri",
            "Lamprima aurata",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },

    "AN": {
        "동물": [
            "Aptenodytes forsteri",
            "Aptenodytes patagonicus",
            "Pygoscelis adeliae",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Orcinus orca",
            "Hydrurga leptonyx",
            "Mirounga leonina",
            "Lobodon carcinophaga",
            "Diomedea exulans",
        ],
        "식물": [
            "Magnolia sieboldii",
            "Pinus koraiensis",
            "Taxus cuspidata",
            "Rhododendron aureum",
            "Abies koreana",
        ],
        "곤충": [
            "Teinopalpus imperialis",
            "Lucanus maculifemoratus",
            "Callipogon relictus",
            "Rosalia batesi",
        ],
        "해양생물": [
            "Chelonia mydas",
            "Caretta caretta",
            "Dermochelys coriacea",
            "Eretmochelys imbricata",
            "Balaenoptera musculus",
            "Megaptera novaeangliae",
            "Carcharodon carcharias",
            "Dugong dugon",
        ],
    },
}

# ========================================
# DEPRECATED: COUNTRY_NAME_TO_CODE
# ========================================
# 이 딕셔너리는 더 이상 사용되지 않습니다.
# iucn_service.py에서 pycountry 라이브러리를 사용하여
# 전 세계 모든 국가명을 자동으로 ISO 코드로 변환합니다.
#
# 하위 호환성을 위해 유지하지만, 새로운 코드에서는 사용하지 마세요.
# ========================================
